HoffInterviewTask/Models/CurrencyResultModel.cs
using System;
using Hoff.InterviewTask.CentralBankClient.Contracts.Types;

namespace Hoff.InterviewTask.Web.Models
{
    /// <summary>
    /// Результат определения курса валюты
    /// </summary>
    public class CurrencyResultModel
    {
        /// <summary>
        /// Дату за которую конвертировали курс
        /// </summary>
        public DateTime Date { get; set; }

        /// <summary>
        /// Валюта для которой определяли курс
        /// </summary>
        public Currency Currency { get; set; }

        /// <summary>
        /// Курс валюты к одному рублю РФ
        /// </summary>
        public decimal Rate { get; set; }
    }
}

HoffInterviewTask/Models/ErrorViewModel.cs
namespace Hoff.InterviewTask.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

HoffInterviewTask/Models/PointModel.cs
namespace Hoff.InterviewTask.Web.Models
{
    /// <summary>
    /// Точка
    /// </summary>
    public class PointModel
    {
        /// <summary>
        /// Координата по оси X
        /// </summary>
        public double X { get; set; }

        /// <summary>
        /// Координата по оси Y
        /// </summary>
        public double Y { get; set; }
    }
}

HoffInterviewTask/Controllers/RatesController.cs
using System;
using System.Diagnostics;
using System.Threading.Tasks;
using Hoff.InterviewTask.CentralBankClient.Contracts;
using Hoff.InterviewTask.CentralBankClient.Contracts.Types;
using Hoff.InterviewTask.CentralBankClient.Exceptions;
using Hoff.InterviewTask.Web.Converters;
using Hoff.InterviewTask.Web.Models;
using Hoff.InterviewTask.Web.Validators.Contracts;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;

namespace Hoff.InterviewTask.Web.Controllers
{
    public class RatesController : Controller
    {
        private readonly IConfiguration _config;
        private readonly ICoordinatesValidator _coordinatesValidator;
        private readonly IRussiaCentralBankClient _rcbClient;
        private readonly ILogger<RatesController> _logger;

        /// <summary>
        /// Конструктор
        /// </summary>
        /// <param name="config">конфиг</param>
        /// <param name="coordinatesValidator">отвечает за валидацию координат и попадаение их в окружность</param>
        /// <param name="rcbClient">клиент для работы с ЦБ РФ</param>
        /// <param name="logger">логгер</param>
        public RatesController(IConfiguration config, ICoordinatesValidator coordinatesValidator, IRussiaCentralBankClient rcbClient, ILogger<RatesController> logger)
        {
            _config = config;
            _coordinatesValidator = coordinatesValidator;
            _rcbClient = rcbClient;
            _logger = logger;
        }

        [HttpGet]

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        [Route("Rates/Coordinate/{x}/{y}")]
        public async Task<IActionResult> GetByCoordinate(double x, double y)
        {
            try
            {
                var point = new PointModel
                            {
                                X = x,
                                Y = y
                            };

                var centerPoint = _config.GetSection("WebSettings:CenterCoordinate").Get<PointModel>();

                var radius = _config.GetValue<double>("WebSettings:Radius");

                if (!_coordinatesValidator.IsValid(centerPoint, radius, point))
                {
                    _logger.Log(LogLevel.Error, $"Переданы координаты x={x}, y={y} которые не попадают в окружность с радиусом {radius}!");

                    return BadRequest($"Переданы координаты которые не попадают в окружность с радиусом {radius}!");
                }

                var date = CoordinatesConverter.ConvertToDate(centerPoint, point);

                var currency = _config.GetValue<Currency>("WebSettings:CurrencyCode");
                var rate = await _rcbClient.GetRateByDate(date, currency);

                var result = new CurrencyResultModel
                             {
                                 Date = date,
                                 Currency = currency,
                                 Rate = rate
                             };

                _logger.Log(LogLevel.Information, $"Для координат x={x}, y={y} получен курс {result.Rate} для валюты {result.Currency} за дату {date:dd.MM.yyyy}");

                return Ok(result);
            }
            catch (CentralBankException e)
            {
                _logger.Log(LogLevel.Error, e, $"Ошибка при попытке получить курс валюты для координат x={x}, y={y}");

                return BadRequest(e.Message);
            }
            catch (Exception e)
            {
                _logger.Log(LogLevel.Error, e, $"Неизвестная ошибка при попытке получить курс валюты для координат x={x}, y={y}");

                return BadRequest("Невозможно определить курс. Попробуйте позже или обратитесь в службу поддержки");
            }
        }
    }
}

HoffInterviewTask/Views/Rates/Index.cshtml
@{
    ViewData["Title"] = "Hoff currency rate";
}

<div class="text-left">
    <h1 class="display-4">Hoff currency rate</h1>
    <p>Введите координаты для определения курса валюты</p>
    
    <form>
        <div class="form-group col-sm-3">
            <label for="xCoord">Координата X</label>
            <input id="xCoord" class="form-control" type="text" placeholder="x">
        </div>

        <div class="form-group col-sm-3">
            <label for="yCoord">Координата Y</label>
            <input id="yCoord" class="form-control" type="text" placeholder="y">
        </div>

        <button id="btnRate" type="button" class="btn btn-success">Получить курс</button>
        
        <div id="message" class="mt-3 invisible alert alert-success" role="alert"></div>
    </form>
</div>

HoffInterviewTask/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HoffInterviewTask</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Rates" asp-action="Index">HoffInterviewTask</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Rates" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - https://github.com/AndreyShp/HoffInterviewTask
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>